name: check

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - release-snapshot
          - 29.1
          - 28.2
          - 27.2
        ignore_warnings:
          - false
    steps:
    - uses: actions/checkout@v2
    - uses: extractions/setup-just@v1
      with:
        just-version: 1.8.0
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@v1.3
      with:
        file: "justl.el"
        check: melpa
        ignore_warnings: ${{ matrix.ignore_warnings }}
        warnings_as_errors: false
    - name: ERT tests
      uses: leotaku/elisp-check@master
      with:
        file: ./test/justl-test.el
        check: ert
        ignore_warnings: ${{ matrix.ignore_warnings }}
        warnings_as_errors: true
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
