name: check

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.2
          - 29.1
          - 28.2
          - 27.2
        ignore_warnings:
          - false
    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v2
      with:
        just-version: 1.10.0
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: cask/setup-cask@v1
      with:
        version: 0.9.0
    - uses: leotaku/elisp-check@v1.3
      with:
        file: "justl.el"
        check: melpa
        ignore_warnings: ${{ matrix.ignore_warnings }}
        warnings_as_errors: false
    - name: Run tests
      run: |
        emacs --version
        cask install
        cask build
        mv test/justfile ./justfile
        cask emacs --batch -L . -L test -f batch-byte-compile $(cask files)
        cask emacs --batch -L . -L test -l test/justl-test.el -f ert-run-tests-batch-and-exit
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
